name: CI
# based on https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/.github/workflows/main.yml
on:
  push:

jobs:
  analyze-oc-config:
    name: Analyze config
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependency
        run: |
          mkdir "OpenCore" && cd "OpenCore" || exit 1
          hg="grep -A 2 OpenCorePkg | grep -m 1 RELEASE"
          rawURL="https://github.com/acidanthera/OpenCorePkg/tags"
          rawURL="https://github.com$(curl -L --silent "${rawURL}" | grep -m 1 'OpenCorePkg' | tr -d '"' | tr -d ' ' | tr -d '>' | sed -e 's/<ahref=//')"
          url="https://github.com$(curl -L --silent "${rawURL}" | grep '/download/' | eval "${hg}" | sed 's/^[^"]*"\([^"]*\)".*/\1/')"
          echo "Downloading ${url##*\/}"
          curl -# -L -O "${url}" || exit 1
          unzip -qq "*.zip" || exit 1
          chmod +x Utilities/ocvalidate/ocvalidate || exit 1

      - name: Run ocvalidate
        run: |
          ./OpenCore/Utilities/ocvalidate/ocvalidate ./EFI/OC/config.plist || exit 1
