name: CI
on:
  push:
  workflow_dispatch:

jobs:
  make-oc-release:
    name: Make EFI (all release)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make EFI (release)
        run: |
          export TARGET=RELEASE
          chmod +x ./scripts/download_oc.sh && ./scripts/download_oc.sh

      - name: Download kext (all release)
        run: |
          export TARGET=Release
          chmod +x ./scripts/download_kext.sh && ./scripts/download_kext.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EFI_RELEASE
          path: EFI/

  make-oc-debug:
    name: Make EFI (all debug)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make EFI (debug)
        run: |
          export TARGET=DEBUG
          chmod +x ./scripts/download_oc.sh && ./scripts/download_oc.sh

      - name: Download kext (all debug)
        run: |
          export TARGET=Debug
          chmod +x ./scripts/download_kext.sh && ./scripts/download_kext.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EFI_DEBUG
          path: EFI/

  analyze-oc-config:
    name: Analyze config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependency
        run: |
          mkdir "OpenCore" && cd "OpenCore" || exit 1
          RELEASE_URL=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/acidanthera/OpenCorePkg/releases/latest)
          TAG="${RELEASE_URL##*/}"
          url=https://github.com/acidanthera/OpenCorePkg/releases/download/$TAG/OpenCore-$TAG-RELEASE.zip
          curl -# -L -O "${url}" || exit 1
          unzip -qq "*.zip" || exit 1
          chmod +x Utilities/ocvalidate/ocvalidate || exit 1
          
      - name: Run ocvalidate
        run: |
          ./OpenCore/Utilities/ocvalidate/ocvalidate.linux ./config/config.plist || exit 1
