name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  analyze-oc-config:
    name: Compare sample & Analyze config
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make script executable
        run: chmod +x ./scripts/AnalyzeConfig.sh
          
      - name: Compare sample & Analyze config
        run: ./scripts/AnalyzeConfig.sh
