name: CI
# based on https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/.github/workflows/main.yml
on:
  push:

jobs:
  make-oc-all:
    name: Make EFIs
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make EFI (release)
        run: |
          chmod +x ./scripts/download_oc_release.sh && ./scripts/download_oc_release.sh

      - name: Download kext (all release)
        run: |
          chmod +x ./scripts/download_kext_release.sh && ./scripts/download_kext_release.sh

      - name: Make EFI (debug)
        run: |
          chmod +x ./scripts/download_oc_debug.sh && ./scripts/download_oc_debug.sh

      - name: Download kext (all debug)
        run: |
          chmod +x ./scripts/download_kext_debug.sh && ./scripts/download_kext_debug.sh

  analyze-oc-config:
    name: Analyze config
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependency
        run: |
          mkdir "OpenCore" && cd "OpenCore" || exit 1
          RELEASE_URL=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/acidanthera/OpenCorePkg/releases/latest)
          TAG="${RELEASE_URL##*/}"
          url=https://github.com/acidanthera/OpenCorePkg/releases/download/$TAG/OpenCore-$TAG-RELEASE.zip
          curl -# -L -O "${url}" || exit 1
          unzip -qq "*.zip" || exit 1
          chmod +x Utilities/ocvalidate/ocvalidate || exit 1
          
      - name: Run ocvalidate
        run: |
          ./OpenCore/Utilities/ocvalidate/ocvalidate ./config/config.plist || exit 1
