name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  make-oc-release:
    name: Make EFI (release)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make script executable
        run: |
          chmod +x ./scripts/BuildOC.sh
          chmod +x ./scripts/BuildKext.sh
          
      - name: Make full EFI
        run: |
         export TARGET=RELEASE
         ./scripts/BuildOC.sh
         ./scripts/BuildKext.sh
        id: ocversion

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: H81M-DS2-EFI_${{ steps.ocversion.outputs.octag }}_${{ steps.ocversion.outputs.buildtarget }}
          path: H81M-DS2-EFI/

  make-oc-debug:
    name: Make EFI (debug)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make script executable
        run: |
          chmod +x ./scripts/BuildOC.sh
          chmod +x ./scripts/BuildKext.sh

      - name: Make full EFI
        run: |
         export TARGET=DEBUG
         ./scripts/BuildOC.sh
         ./scripts/BuildKext.sh
        id: ocversion

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: H81M-DS2-EFI_${{ steps.ocversion.outputs.octag }}_${{ steps.ocversion.outputs.buildtarget }}
          path: H81M-DS2-EFI/

  analyze-oc-config:
    name: Analyze config
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependency
        run: |
          mkdir "OpenCore" && cd "OpenCore" || exit 1
          RELEASE_URL=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/acidanthera/OpenCorePkg/releases/latest)
          TAG="${RELEASE_URL##*/}"
          echo "::set-output name=octag::${TAG}"
          url=https://github.com/acidanthera/OpenCorePkg/releases/download/$TAG/OpenCore-$TAG-RELEASE.zip
          curl -# -L -O "${url}" || exit 1
          unzip -qq "*.zip" || exit 1
          chmod +x Utilities/ocvalidate/ocvalidate || exit 1
        id: ocversion
          
      - name: Run ocvalidate
        run: |
          ./OpenCore/Utilities/ocvalidate/ocvalidate ./config/${{ steps.ocversion.outputs.octag }}/config.plist || exit 1
          ./OpenCore/Utilities/ocvalidate/ocvalidate ./config/${{ steps.ocversion.outputs.octag }}/config_igpu.plist || exit 1
